/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ログイン
     * @description ユーザー認証を行い、JWTトークンを発行します
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description ログイン成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResponse'];
          };
        };
        /** @description リクエストエラー */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description 認証失敗 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * ログアウト
     * @description ユーザーのセッションを終了します
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ログアウト成功 */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 認証エラー */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ログインユーザー情報取得
     * @description 現在ログインしているユーザーの情報を取得します
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ユーザー情報取得成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        /** @description 認証エラー */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 日報一覧取得
     * @description 日報の一覧を取得します
     */
    get: {
      parameters: {
        query?: {
          /** @description 開始日 */
          start_date?: string;
          /** @description 終了日 */
          end_date?: string;
          /** @description 営業担当者ID */
          sales_person_id?: number;
          /** @description ページ番号 */
          page?: number;
          /** @description 1ページあたりの件数 */
          per_page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 日報一覧取得成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: components['schemas']['DailyReportListItem'][];
              pagination?: components['schemas']['Pagination'];
            };
          };
        };
        /** @description 認証エラー */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * 日報作成
     * @description 新しい日報を作成します
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateReportRequest'];
        };
      };
      responses: {
        /** @description 日報作成成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: number;
              /** Format: date */
              report_date?: string;
              sales_person_id?: number;
              problem?: string;
              plan?: string;
              /** Format: date-time */
              created_at?: string;
            };
          };
        };
        /** @description リクエストエラー */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description 同じ日付の日報が既に存在します */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 顧客一覧取得
     * @description 顧客の一覧を取得します
     */
    get: {
      parameters: {
        query?: {
          /** @description 検索キーワード（会社名/担当者名） */
          search?: string;
          /** @description ページ番号 */
          page?: number;
          /** @description 1ページあたりの件数 */
          per_page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 顧客一覧取得成功 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: components['schemas']['Customer'][];
              pagination?: components['schemas']['Pagination'];
            };
          };
        };
        /** @description 認証エラー */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * 顧客作成
     * @description 新しい顧客を作成します（管理者のみ）
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateCustomerRequest'];
        };
      };
      responses: {
        /** @description 顧客作成成功 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Customer'];
          };
        };
        /** @description リクエストエラー */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description 権限エラー（管理者のみ） */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        details?: {
          field?: string;
          message?: string;
        }[];
      };
    };
    Pagination: {
      total: number;
      page: number;
      per_page: number;
      total_pages: number;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      token: string;
      /** Format: date-time */
      expires_at: string;
      user: components['schemas']['User'];
    };
    User: {
      id: number;
      name: string;
      /** Format: email */
      email: string;
      department: string;
      is_manager: boolean;
    };
    SalesPerson: {
      id: number;
      name: string;
      /** Format: email */
      email: string;
      department: string;
      is_manager: boolean;
    };
    CreateSalesPersonRequest: {
      name: string;
      /** Format: email */
      email: string;
      password: string;
      department: string;
      is_manager: boolean;
    };
    Customer: {
      id: number;
      company_name: string;
      contact_person: string;
      phone: string;
      /** Format: email */
      email: string;
    };
    CreateCustomerRequest: {
      company_name: string;
      contact_person: string;
      phone: string;
      /** Format: email */
      email: string;
      address?: string;
    };
    DailyReportListItem: {
      id: number;
      /** Format: date */
      report_date: string;
      sales_person: {
        id?: number;
        name?: string;
      };
      visit_count: number;
      has_comments: boolean;
      /** Format: date-time */
      created_at: string;
    };
    CreateReportRequest: {
      /** Format: date */
      report_date: string;
      problem: string;
      plan: string;
      visits: {
        customer_id: number;
        visit_time?: string;
        visit_content: string;
      }[];
    };
    CreateCommentRequest: {
      comment: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
